language: python
python:
    - "3.7"

services:
    - docker

before_install:
    - - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin

before_script: pip install docker-compose

script:
    - POSTGRES_NAME=postgres_recipe NETWORK_NAME=network_recipe APP_NAME=recipe_app_api docker-compose run app sh -c "python manage.py wait_for_db && python manage.py test && flake8"
