version: "3"

services:
    app: # service name
        build:
            context: .
        container_name: ${APP_NAME}
        ports: # mapping ports between host and container
            - "8000:8000" # "host_port:container_port"
        volumes:
            - ./app:/app
        command: >
            sh -c "python manage.py wait_for_db &&
                   python manage.py migrate &&
                   python manage.py runserver 0.0.0.0:8000"
        environment:
            - DB_HOST=${POSTGRES_NAME}
            - DB_NAME=app
            - DB_USER=postgres
            - DB_PASS=secretPassword
        depends_on:
            - db
    db:
        image: postgres:10-alpine
        container_name: ${POSTGRES_NAME}
        ports:
            - "5438:5432"
        environment:
            - POSTGRES_DB=app
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=secretPassword
